<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.hyze.skyblock</groupId>
        <artifactId>framework-parent</artifactId>
        <version>0.1</version>
    </parent>

    <artifactId>framework-plugin</artifactId>
    <name>SkyBlock-Framework</name>
    <packaging>jar</packaging>

    <repositories>
        <repository>
            <id>sk89q-repo</id>
            <url>http://maven.sk89q.com/artifactory/repo/</url>
        </repository>
    </repositories>
    
    <dependencies>
        
        <!-- Skyblock API -->
        <dependency>
            <groupId>net.hyze.skyblock</groupId>
            <artifactId>framework-api</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        
        <dependency>
            <groupId>net.hyze</groupId>
            <artifactId>core-spigot</artifactId>
            <version>0.1</version>
        </dependency>

        <!--Spigot API-->
        <dependency>
            <groupId>org.github.paperspigot</groupId>
            <artifactId>paperspigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <!--Spigot API-->
        <dependency>
            <groupId>org.github.paperspigot</groupId>
            <artifactId>paperspigot</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <!--ProtocolLib-API-->
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Slime -->
        <dependency>
            <groupId>net.hyze</groupId>
            <artifactId>slime</artifactId>
            <version>0.1</version>
        </dependency>
        
        <!-- Citizens -->
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizens</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <!-- WorldEdit -->
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>6.1.4-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>com.github.luben:zstd-jni</include>
                                    <include>net.hyze:seaweedfs-client</include>
                                    <include>net.hyze:slime</include>
                                    <include>net.hyze.skyblock:framework-api</include>
                                    <include>org.apache.httpcomponents:*</include>
                                </includes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
